apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress-internal
  namespace: httpbin
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    nginx.ingress.kubernetes.io/server-snippet: |
      real_ip_header      X-Forwarded-For;
      real_ip_recursive   on;
      set_real_ip_from    0.0.0.0/0;
      
      map $http_x_forwarded_for $custom_full_x_forwarded_for {
          default          "$http_x_forwarded_for, $realip_remote_addr";
          ''               "$realip_remote_addr";
      }
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $custom_full_x_forwarded_for;
spec:
  ingressClassName: nginx-internal
  rules:
    - host: httpbin-internal.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 80
