apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress-internal
  namespace: httpbin
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
spec:
  ingressClassName: nginx-internal
  rules:
    - host: httpbin-internal.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 80
