apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress-public
  namespace: httpbin
  annotations:
    kubernetes.io/ingress.class: "nginx-public"
spec:
  rules:
    - host: httpbin-public.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 80
# curl -H 'Host: httpbin-public.local' 172.18.255.200